import { View } from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaView } from "@/components/safe-area-view";
import { Button } from "@/components/ui/button";
import { Text } from "@/components/ui/text";
import { H1, Muted } from "@/components/ui/typography";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Ionicons } from "@expo/vector-icons";
import { colors } from "@/constants/colors";
import { storageIdentifiers } from "@/constants/storage";

export default function DisclaimerModal() {
	const router = useRouter();

	const handleAccept = async () => {
		try {
			await AsyncStorage.setItem(storageIdentifiers.hasSeenDisclaimer, "true");
			router.back();
		} catch (error) {
			console.error("Error saving disclaimer status:", error);
		}
	};

	return (
		<SafeAreaView className="flex-1 bg-zinc-900">
			<View className="flex-1 px-6 py-8">
				<View className="items-center mb-12">
					<View className="w-16 h-16 bg-primary/10 rounded-full items-center justify-center mb-6">
						<Ionicons
							name="information"
							size={32}
							color={colors.dark.primary}
						/>
					</View>
					<H1 className="text-3xl font-bold mb-2 text-center">
						Important Notice
					</H1>
					<Muted className="text-base text-center">Please read carefully</Muted>
				</View>

				<View className="flex-1 justify-center space-y-8">
					<View className=" rounded-2xl p-6">
						<View className="flex-row items-start mb-4">
							<View className="w-8 h-8 bg-primary/10 rounded-full items-center justify-center mr-4 mt-1">
								<Ionicons
									name="chatbubbles-outline"
									size={14}
									color={colors.dark.primary}
								/>
							</View>
							<Text className="flex-1 text-base text-foreground leading-6">
								Please be aware that conversations in this app are generated by
								artificial intelligence. While we strive for accuracy and
								appropriateness, the responses may not always be perfect or
								completely accurate.
							</Text>
						</View>

						<View className="flex-row items-start">
							<View className="w-8 h-8 bg-primary/10 rounded-full items-center justify-center mr-4 mt-1">
								<Ionicons
									name="alert-circle-outline"
									size={14}
									color={colors.dark.primary}
								/>
							</View>
							<Text className="flex-1 text-base text-foreground leading-6">
								If you encounter any inappropriate or offensive content, please
								report it through the Contact Us section in your profile.
							</Text>
						</View>
					</View>
				</View>

				<Button
					size="lg"
					variant="default"
					onPress={handleAccept}
					className="mt-auto"
				>
					<View className="flex-row items-center space-x-2">
						<Text className="text-primary-foreground font-medium">
							I Understand
						</Text>
					</View>
				</Button>
			</View>
		</SafeAreaView>
	);
}
